#!/bin/sh

JAVA="/usr/bin/java"
CL_HOME="/tmp"
JAR="couchdb-lucene-0.5.jar"

# Basic settings
JAVA_OPTS="-server"

# Capture errors
JAVA_OPTS="$JAVA_OPTS -XX:ErrorFile=$CL_HOME/cl-error.log -XX:HeapDumpPath=/tmp/cl.prof -XX:-HeapDumpOnOutOfMemoryError"


$JAVA $JAVA_OPTS -jar $JAR
